name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    container:
      image: mcr.microsoft.com/playwright:v1.28.1-jammy
      options: --init --ipc=host --user=1001
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
        name: Install pnpm
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 16
      - name: Install dependencies
        run: pnpm install
      - name: Run Playwright tests
        run: pnpm playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
